apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-api-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rest-api-app
  template:
    metadata:
      labels:
        app: rest-api-app
    spec:
      containers:
        - name: app
          image: rest-api-demo:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: rest-api-app-svc
spec:
  selector:
    app: rest-api-app
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP

